//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Kaynaklar {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proje.Kaynaklar.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ANASAYFA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   basket topu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string basketTopu {
            get {
                return ResourceManager.GetString("basketTopu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇOÇUK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cocuk {
            get {
                return ResourceManager.GetString("cocuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERKEK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string erkek {
            get {
                return ResourceManager.GetString("erkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   erkek ayakkabısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Erkekayakkabi {
            get {
                return ResourceManager.GetString("Erkekayakkabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erkek coçuk ayakkabısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Erkekcocukayakkabi {
            get {
                return ResourceManager.GetString("Erkekcocukayakkabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İncele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string incele {
            get {
                return ResourceManager.GetString("incele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KADIN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kadin {
            get {
                return ResourceManager.GetString("kadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kadın ayakkabısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kadinayakkabi {
            get {
                return ResourceManager.GetString("kadinayakkabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kız çoçuk ayakkabısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kizcocukayakkabi {
            get {
                return ResourceManager.GetString("Kizcocukayakkabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-MAİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mavi cüzdan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mavicuzdan {
            get {
                return ResourceManager.GetString("mavicuzdan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string oturumac {
            get {
                return ResourceManager.GetString("oturumac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sepet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sepet {
            get {
                return ResourceManager.GetString("sepet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPOR MALZEMELERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string spor {
            get {
                return ResourceManager.GetString("spor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yonet {
            get {
                return ResourceManager.GetString("yonet", resourceCulture);
            }
        }
    }
}
