//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int UrunId { get; set; }
        public string UrunCinsiyet { get; set; }
        public string UrunResim { get; set; }
        public Nullable<int> UrunFiyat { get; set; }
        public string UrunMarka { get; set; }
    }
}
